import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 11,
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 50,
    backgroundColor: "#ffffff",
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#2563eb",
    paddingBottom: 10,
  },
  name: {
    fontSize: 24,
    fontFamily: "Helvetica-Bold",
    color: "#1e293b",
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: "#2563eb",
    marginTop: 16,
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingBottom: 3,
  },
  bullet: {
    flexDirection: "row",
    marginBottom: 4,
    paddingLeft: 8,
  },
  bulletDot: {
    width: 12,
    color: "#2563eb",
    fontFamily: "Helvetica-Bold",
  },
  bulletText: {
    flex: 1,
    color: "#334155",
    lineHeight: 1.5,
  },
  summaryText: {
    color: "#334155",
    lineHeight: 1.6,
    marginBottom: 4,
  },
  improvedBadge: {
    fontSize: 8,
    color: "#16a34a",
    fontFamily: "Helvetica-Bold",
    marginLeft: 4,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 50,
    right: 50,
    textAlign: "center",
    fontSize: 8,
    color: "#94a3b8",
  },
});

interface Rewrite {
  section: string;
  original: string;
  rewritten: string;
  explanation: string;
}

interface ResumePDFProps {
  fileName: string;
  rawText: string;
  rewrites: Rewrite[];
  improvedSummary: string | null;
}

export default function ResumePDF({
  fileName,
  rawText,
  rewrites,
  improvedSummary,
}: ResumePDFProps) {
  // Group rewrites by section
  const rewriteMap = new Map<string, Rewrite[]>();
  rewrites.forEach((r) => {
    if (!rewriteMap.has(r.section)) {
      rewriteMap.set(r.section, []);
    }
    rewriteMap.get(r.section)!.push(r);
  });

  const sections = Array.from(rewriteMap.entries());

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.name}>
            {fileName.replace(/\.(pdf|docx)$/i, "")}
          </Text>
          <Text style={{ fontSize: 9, color: "#64748b" }}>
            AI-Optimized Resume — Generated by AI Career Copilot
          </Text>
        </View>

        {/* Improved Summary */}
        {improvedSummary && (
          <View>
            <Text style={styles.sectionTitle}>Professional Summary ✓</Text>
            <Text style={styles.summaryText}>{improvedSummary}</Text>
          </View>
        )}

        {/* Rewritten Sections */}
        {sections.map(([section, sectionRewrites]) => (
          <View key={section}>
            <Text style={styles.sectionTitle}>{section}</Text>
            {sectionRewrites.map((rewrite, index) => (
              <View key={index} style={styles.bullet}>
                <Text style={styles.bulletDot}>•</Text>
                <Text style={styles.bulletText}>
                  {rewrite.rewritten}
                  <Text style={styles.improvedBadge}> ✓ improved</Text>
                </Text>
              </View>
            ))}
          </View>
        ))}

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by AI Career Copilot • Resume optimized with AI
        </Text>
      </Page>
    </Document>
  );
}